# Generated by Django 4.1.7 on 2023-02-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('store', models.IntegerField()),
                ('image', models.URLField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
